services:
  db:
    image: postgis/postgis:15-3.3
    container_name: renter_db
    # image: ... (刪除原本的 image 這一行)
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: renter_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: jushengtin2@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    ports:
      - "5051:80"
    depends_on:
      - db
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:latest
    container_name: renter_redis
    ports:
      - "8787:6379"
    volumes:
      - ./redis_data:/data

  redis-gui:
    image: redislabs/redisinsight:latest
    container_name: renter_redis_gui
    environment:
      - REDIS_HOSTS=local:redis:8788
    ports:
      - "8788:5540"
    depends_on:
      - redis

  ngrok:
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=3AOC7EejyuE8Igmzj2ObBpeoqIH_Av1zJvHywJHzKXn9P2H3
    ports:
      - "4040:4040"
    command:
      - "http"
      - "host.docker.internal:8080" # 關鍵：指向你電腦終端機跑的 8080
    # 這裡不需要 depends_on: server，因為 server 沒跑在 Docker 裡
