name: Deploy Backend to GCP Cloud Run

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: project-c0a608b0-a22f-495a-aa8
  SERVICE_NAME: hazukashii-backend
  REGION: asia-east1
  REPO_NAME: hazukashii-artifact-registry

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"

      # - name: Run Tests
      #   run: go test ./...

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Docker Auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push
        run: |
          TAG=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          docker build -t $TAG .
          docker push $TAG

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --project ${{ env.PROJECT_ID }} \
            --set-secrets "APP_ENV=app-env:latest,GCS_BUCKET_NAME=hazukashii_picture_storage:latest,SUPABASE_DB_URL=supabase-db-url:latest,SUPABASE_STORAGE_URL=supabase-storage-url:latest,SUPABASE_KEY_ID=supabase-key-id:latest,SUPABASE_ACCESS_KEY=supabase-access-key:latest,SUPABASE_REGION=supabase-region:latest,CLERK_JWKS_URL=clerk-jwks-url:latest,CLERK_PRIVATE_KEY=clerk-private-key:latest,CLERK_WEBHOOK_SIGNING_SECRET=clerk-webhook-signing-secret:latest,CLERK_WEBHOOK_PATH=clerk-webhook-path:latest" \
            --platform managed \
            --allow-unauthenticated \
            --quiet
