name: Deploy Backend to GCP Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: project-c0a608b0-a22f-495a-aa8
  SERVICE_NAME: hazukashii-backend
  REGION: asia-east1
  REPO_NAME: hazukashii-artifact-registry

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"

      # - name: Run Tests
      #   run: go test ./...

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Docker Auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push
        run: |
          TAG=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          docker build -t $TAG .
          docker push $TAG

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --project ${{ env.PROJECT_ID }} \
            --set-env-vars "SUPABASE_DB_URL=${{ secrets.SUPABASE_DB_URL }},SUPABASE_KEY=${{ secrets.SUPABASE_KEY }},CLERK_JWKS_URL=${{ secrets.CLERK_JWKS_URL }},CLERK_PRIVATE_KEY=${{ secrets.CLERK_PRIVATE_KEY }},GCS_BUCKET_NAME=${{secrets.GCS_BUCKET_NAME}}" \
            --platform managed \
            --allow-unauthenticated \
            --quiet
